//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "unrecognized_words")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: u64,
    #[sea_orm(column_type = "Text")]
    pub form: String,
    pub encountered: Option<Date>,
    pub lookup_attempted: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
